pipeline:
  buildGO:
    image: golang
    commands:
      - cd /drone/src/github.com/capgemini-devops-bootcamp/BootcampPortal/test
      - go build
  buildImage:
    image: plugins/docker
    username: AWS
    password: ${DOCKER_PASSWORD}
    repo: andyclear/bootcamp
    tags: latest
    dockerfile: test/Dockerfile
