pipeline:
  buildImage:
    image: plugins/docker
    username: devopsbootcamp
    password: ${DHUB_PASSWORD}
    repo: capgeminidevopsbootcamp/bootcamp-app
    tags: latest
    debug: true
    context: UI/frontend-react/hello-world/
 # deploy:
  #  image: vallard/drone-kube
   # template: kubernetes/deploy.yaml
    #server: https://10.0.0.10:6443
    #token: ${KUBE_TOKEN}
    #ca: ${KUBE_CA}