pipeline:
  buildGO:
    image: golang
    commands:
      - cd /drone/src/github.com/capgemini-devops-bootcamp/BootcampPortal/test
      - go build
  buildImage:
    image: plugins/docker
    username: devopsbootcamp
    password: ${DHUB_PASSWORD}
    repo: capgeminidevopsbootcamp/bootcamp-app
    tags: latest
    dockerfile: test/Dockerfile 
  deploy:
    image: vallard/drone-kube
    template: kubernetes/deploy.yaml
    server: https://10.0.0.71:6443
    
