pipeline:
  buildGO:
    image: golang
    commands:
      - cd /drone/src/github.com/capgemini-devops-bootcamp/BootcampPortal/test
      - go build
    when:
      branch: master
  buildImage:
    image: plugins/docker
    username: devopsbootcamp
    password: ${DHUB_PASSWORD}
    repo: capgeminidevopsbootcamp/bootcamp-app
    tags: latest
    dockerfile: test/Dockerfile
    when:
      branch: master
  deploy:
    image: vallard/drone-kube
    template: kubernetes/deploy.yaml
    server: https://10.0.0.10:6443
    token: ${KUBE_TOKEN}
    ca: ${KUBE_CA}
    when:
      branch: master
