pipeline:
  buildGO:
    image: golang
    commands:
      - cd /drone/src/github.com/capgemini-devops-bootcamp/BootcampPortal/test
      - go build
  buildImage:
    image: plugins/docker
    username: andyclear
    password: ${dockerPassword}
    repo: andyclear/bootcamp
    tags: latest
    dockerfile: test/Dockerfile 
  deploy:
    image: vallard/drone-kube
    template: kubernetes/deploy.yaml
