---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bootcamp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: bootcamp
    spec:
      containers:
      - name: bootcamp
        image: capgeminidevopsbootcamp/bootcamp-app
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: bootcamp-service
spec:
  type: "NodePort"
  selector:
    app: bootcamp
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000
